version: "3.8"
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        volumes:
            - ./backend:/app
            - backend_node_modules:/app/node_modules
        ports:
            - 3000:3000
        environment:
            - NODE_ENV=development
            - DATABASE_URL=${DATABASE_URL}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - SECRET=${SECRET}
        depends_on:
            - frontend
            - db

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
            - ./frontend:/app
            - frontend_node_modules:/app/node_modules
        ports:
            - 5173:5173
        environment:
            - NODE_ENV=development
        command: npm run dev -- --host

    db:
        image: postgres:16
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
    frontend_node_modules:
    backend_node_modules:
