version: "3.8"
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        volumes:
            - ./backend:/app
            - backend_node_modules:/app/node_modules
        environment:
            - NODE_ENV=development
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - SECRET=${SECRET}
        depends_on:
            - frontend
            - db

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
            - ./frontend:/app
            - frontend_node_modules:/app/node_modules
        environment:
            - NODE_ENV=development
        command: npm run dev -- --host

    db:
        image: postgres:16
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - pgdata:/var/lib/postgresql/data

    nginx:
        image: nginx:1.25
        ports:
            - 8080:80
        volumes:
            - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
        container_name: reverse-proxy
        depends_on:
            - frontend
            - backend
            - db

volumes:
    pgdata:
    frontend_node_modules:
    backend_node_modules:
