name: Deploy Workflow

on:
    pull_request:
        branches: [main]
        types: [closed]
jobs:
    deploy-app:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set image tag
              id: vars
              run: echo "TAG=$(date +%Y%m%d%H%M%S)-${{ github.sha }}" >> $GITHUB_OUTPUT

            - name: Log in to Docker Hub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "aitoaarni" --password-stdin

            - name: Build and push Docker image
              run: docker build -t "aitoaarni/typing-game-backend:${{ steps.vars.outputs.TAG}}" ./backend/

            - name: Push Docker image
              run: docker push aitoaarni/typing-game-backend:${{ steps.vars.outputs.TAG}}

            - name: Trigger Railway Redeploy
              env:
                  RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
                  ENV_ID: ${{ secrets.RAILWAY_BACKEND_ENVIRONMENT_ID }}

              run: |
                  curl -X POST https://backboard.railway.app/graphql/v2 \
                  -H "Authorization: Bearer $RAILWAY_TOKEN" \
                  -H "Content-Type: application/json" \
                  --data "$(jq -n \
                    --arg envId "$ENV_ID" \
                    '{ query: "mutation Redeploy($input: RedeployEnvironmentInput!) { redeployEnvironment(input: $input) { id } }", variables: { input: { environmentId: $envId } } }')"
